name: Build and Deploy React App AWS S3

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentias@v1
        with:
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1
      - name: Build project
        run: npm install && npm run build
      - name: Deploy para AWS S3
        run: aws s3 sync ./build/ s3://reactbasic --delete